name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push the Docker image
        env:
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:example-reported-image
        run: |
          docker build . --file Dockerfile --tag $CF_IMAGE && docker push $CF_IMAGE
      - name: report image by action
        with:
          CF_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/csdp-report-image-github-action:example-reported-image
          CF_ENRICHERS: "jira, git"
          # Specify cluster app-proxy
          CF_HOST: "https://eti.pipeline-team.cf-cd.com"
          CF_VERBOSE: "1"
          CF_API_KEY: ${{ secrets.ETI_TOKEN }}
          CF_CONTAINER_REGISTRY_INTEGRATION: "quay"
          "CF_GITHUB_TOKEN": ${{ secrets.G_TOKEN }}
          "CF_GIT_PROVIDER": "github"
          "CF_GIT_REPO": "codefresh-io/example-github-action-use-csdp-report-image"
          "CF_GIT_BRANCH": "feature"
          "CF_JIRA_INTEGRATION": "jira"
          "CF_JIRA_MESSAGE": "wip CR-11027"
          "CF_JIRA_PROJECT_PREFIX": "CR"
        uses: codefresh-io/csdp-report-image@0.0.40


